# Spotify "Top 50" playlist IDs by country
# Full list: https://developer.spotify.com/documentation/web-api
COUNTRIES = {
    "Global":         "37i9dQZEVXbMDoHDwVN2tF",
    "Brazil":         "37i9dQZEVXbKzoK95AbRy9",
    "USA":            "37i9dQZEVXbLRQDuF5jeBp",
    "UK":             "37i9dQZEVXbLnolsZ8PSNw",
    "Germany":        "37i9dQZEVXbJiZcmkrIHGU",
    "France":         "37i9dQZEVXbIPWwFssbupI",
    "Spain":          "37i9dQZEVXbNFJfN1Vw8d9",
    "Italy":          "37i9dQZEVXbIQnj7RRhdSX",
    "Mexico":         "37i9dQZEVXbO3qyFxbkOE1",
    "Argentina":      "37i9dQZEVXbMMy2YRppEeZ",
    "Colombia":       "37i9dQZEVXbOa2lmxNMihs",
    "Chile":          "37i9dQZEVXbL0GavIqMTeb",
    "Canada":         "37i9dQZEVXbKj23U1GF4IR",
    "Australia":      "37i9dQZEVXbK4fwx2r07XW",
    "Japan":          "37i9dQZEVXbKXQ4mDTEBXq",
    "South Korea":    "37i9dQZEVXbNxXF4SkHj9F",
    "India":          "37i9dQZEVXbLZ52XmnySJg",
    "Sweden":         "37i9dQZEVXbLoATJ81isYy",
    "Netherlands":    "37i9dQZEVXbKCF6dqVpDkS",
    "Poland":         "37i9dQZEVXbN6itCcaL3Tt",
    "Portugal":       "37i9dQZEVXbKyJS56d1pgi",
    "Turkey":         "37i9dQZEVXbIVYVBNw9D5K",
    "South Africa":   "37i9dQZEVXbMH2jvi6jvjk",
    "Nigeria":        "37i9dQZEVXbKY7jLzlJ11V",
    "Indonesia":      "37i9dQZEVXbObFQZ3JLcXt",
}
